fixing

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -7,8 +7,8 @@
 COMMIT_MESSAGE=$(cat $1)
 
 if [[ ! $COMMIT_MESSAGE =~ ^(feat|fix|refactor|test|docs|core) ]]; then
-    echo "Error: Commit message must start with one of the following keywords: feat, fix, refactor, test, docs, core."
-    exit 1
+  echo "Error: Commit message must start with one of the following keywords: feat, fix, refactor, test, docs, core."
+  exit 1
 fi
 
 exit 0
